/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DriverTableRouteImport } from './routes/driverTable'
import { Route as EntrantInputRouteImport } from './routes/entrantInput'
import { Route as EntrantTableRouteImport } from './routes/entrantTable'
import { Route as FsRouteImport } from './routes/fs'
import { Route as TableRouteImport } from './routes/table'
import { Route as VehicleInputRouteImport } from './routes/vehicleInput'
import { Route as VehicleTableRouteImport } from './routes/vehicleTable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTableRoute = DriverTableRouteImport.update({
  id: '/driverTable',
  path: '/driverTable',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrantInputRoute = EntrantInputRouteImport.update({
  id: '/entrantInput',
  path: '/entrantInput',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrantTableRoute = EntrantTableRouteImport.update({
  id: '/entrantTable',
  path: '/entrantTable',
  getParentRoute: () => rootRouteImport,
} as any)
const FsRoute = FsRouteImport.update({
  id: '/fs',
  path: '/fs',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleInputRoute = VehicleInputRouteImport.update({
  id: '/vehicleInput',
  path: '/vehicleInput',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleTableRoute = VehicleTableRouteImport.update({
  id: '/vehicleTable',
  path: '/vehicleTable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/driverTable': typeof DriverTableRoute
  '/entrantInput': typeof EntrantInputRoute
  '/entrantTable': typeof EntrantTableRoute
  '/fs': typeof FsRoute
  '/table': typeof TableRoute
  '/vehicleInput': typeof VehicleInputRoute
  '/vehicleTable': typeof VehicleTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/driverTable': typeof DriverTableRoute
  '/entrantInput': typeof EntrantInputRoute
  '/entrantTable': typeof EntrantTableRoute
  '/fs': typeof FsRoute
  '/table': typeof TableRoute
  '/vehicleInput': typeof VehicleInputRoute
  '/vehicleTable': typeof VehicleTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/driverTable': typeof DriverTableRoute
  '/entrantInput': typeof EntrantInputRoute
  '/entrantTable': typeof EntrantTableRoute
  '/fs': typeof FsRoute
  '/table': typeof TableRoute
  '/vehicleInput': typeof VehicleInputRoute
  '/vehicleTable': typeof VehicleTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/driverTable'
    | '/entrantInput'
    | '/entrantTable'
    | '/fs'
    | '/table'
    | '/vehicleInput'
    | '/vehicleTable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/driverTable'
    | '/entrantInput'
    | '/entrantTable'
    | '/fs'
    | '/table'
    | '/vehicleInput'
    | '/vehicleTable'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/driverTable'
    | '/entrantInput'
    | '/entrantTable'
    | '/fs'
    | '/table'
    | '/vehicleInput'
    | '/vehicleTable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DriverTableRoute: typeof DriverTableRoute
  EntrantInputRoute: typeof EntrantInputRoute
  EntrantTableRoute: typeof EntrantTableRoute
  FsRoute: typeof FsRoute
  TableRoute: typeof TableRoute
  VehicleInputRoute: typeof VehicleInputRoute
  VehicleTableRoute: typeof VehicleTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driverTable': {
      id: '/driverTable'
      path: '/driverTable'
      fullPath: '/driverTable'
      preLoaderRoute: typeof DriverTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrantInput': {
      id: '/entrantInput'
      path: '/entrantInput'
      fullPath: '/entrantInput'
      preLoaderRoute: typeof EntrantInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrantTable': {
      id: '/entrantTable'
      path: '/entrantTable'
      fullPath: '/entrantTable'
      preLoaderRoute: typeof EntrantTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fs': {
      id: '/fs'
      path: '/fs'
      fullPath: '/fs'
      preLoaderRoute: typeof FsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicleInput': {
      id: '/vehicleInput'
      path: '/vehicleInput'
      fullPath: '/vehicleInput'
      preLoaderRoute: typeof VehicleInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicleTable': {
      id: '/vehicleTable'
      path: '/vehicleTable'
      fullPath: '/vehicleTable'
      preLoaderRoute: typeof VehicleTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DriverTableRoute: DriverTableRoute,
  EntrantInputRoute: EntrantInputRoute,
  EntrantTableRoute: EntrantTableRoute,
  FsRoute: FsRoute,
  TableRoute: TableRoute,
  VehicleInputRoute: VehicleInputRoute,
  VehicleTableRoute: VehicleTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
