/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DriverTableRouteImport } from './routes/driverTable'
import { Route as EntrantTableRouteImport } from './routes/entrantTable'
import { Route as FsRouteImport } from './routes/fs'
import { Route as VehicleTableRouteImport } from './routes/vehicleTable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTableRoute = DriverTableRouteImport.update({
  id: '/driverTable',
  path: '/driverTable',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrantTableRoute = EntrantTableRouteImport.update({
  id: '/entrantTable',
  path: '/entrantTable',
  getParentRoute: () => rootRouteImport,
} as any)
const FsRoute = FsRouteImport.update({
  id: '/fs',
  path: '/fs',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleTableRoute = VehicleTableRouteImport.update({
  id: '/vehicleTable',
  path: '/vehicleTable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/driverTable': typeof DriverTableRoute
  '/entrantTable': typeof EntrantTableRoute
  '/fs': typeof FsRoute
  '/vehicleTable': typeof VehicleTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/driverTable': typeof DriverTableRoute
  '/entrantTable': typeof EntrantTableRoute
  '/fs': typeof FsRoute
  '/vehicleTable': typeof VehicleTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/driverTable': typeof DriverTableRoute
  '/entrantTable': typeof EntrantTableRoute
  '/fs': typeof FsRoute
  '/vehicleTable': typeof VehicleTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/driverTable' | '/entrantTable' | '/fs' | '/vehicleTable'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/about' | '/driverTable' | '/entrantTable' | '/fs' | '/vehicleTable'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/driverTable'
    | '/entrantTable'
    | '/fs'
    | '/vehicleTable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DriverTableRoute: typeof DriverTableRoute
  EntrantTableRoute: typeof EntrantTableRoute
  FsRoute: typeof FsRoute
  VehicleTableRoute: typeof VehicleTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driverTable': {
      id: '/driverTable'
      path: '/driverTable'
      fullPath: '/driverTable'
      preLoaderRoute: typeof DriverTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrantTable': {
      id: '/entrantTable'
      path: '/entrantTable'
      fullPath: '/entrantTable'
      preLoaderRoute: typeof EntrantTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fs': {
      id: '/fs'
      path: '/fs'
      fullPath: '/fs'
      preLoaderRoute: typeof FsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicleTable': {
      id: '/vehicleTable'
      path: '/vehicleTable'
      fullPath: '/vehicleTable'
      preLoaderRoute: typeof VehicleTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DriverTableRoute: DriverTableRoute,
  EntrantTableRoute: EntrantTableRoute,
  FsRoute: FsRoute,
  VehicleTableRoute: VehicleTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
